title: Aziz's small blog
email: f"{fname.lower()}.{lname.lower()}@gmail.com"
author: Aziz Fouché
description: >-
  Personal blog, notes, and thoughts.
baseurl: ""
url: "https://az-fouche.github.io"
github_username: az-fouche
linkedin_username: aziz-fouche
scholar_url: https://scholar.google.fr/citations?user=Am0OkmkAAAAJ

theme: minima
header_pages:
  - resume.md
  - posts.md
  - about.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
permalink: /:year/:month/:day/:title/
timezone: Europe/Paris

minima:
  date_format: "%Y-%m-%d"

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - .bundle
  - README.md
